### ISSUE TITLE
Buttons with relative paths

### ISSUE THREAD

**Issue by thinkJD** [bruderstein/PythonScript#15]
Hi,
first i love this plugin, thanks for the great work! 

I have a problem assigning the toolbar icons for scripts.
I replaced the absolute paths in "PythonScriptStartup.cnf" to relative ones to keep the notepad++ installation portable.
Then it comes to a strage behavior. I can click the icon only one time. A new start of the script is then only over the menu or after a restart possible.

**Comment by MaDill** [comment]
Hi,

it would be good when the path in the configuration is stored relative to the plugin directory. Then notepad++ could be used really portable. At the moment the only chance is to manually edit the configuration file.

This should apply also for the menu stuff. I want to add some shortcuts to my scripts and this is only possible when add them to the menu.

In the LUA Script plugin there is a AddShortcut function. Together with the GetPluginsConfigDir function I could use this to register the shortcuts. This works portable. Maybe this can be added to Python Script also. Then I can call this in the startup.py

I use version 1.0.8 of the plugin.

**Comment by ClaudiaFrank** [comment]
wip
Currently I have something in mind like this

```
ITEM/RunCurrentScript.py
ITEM/AnotherMultiEdit.py
ITEM/RegexTesterProx64.py
ITEM/Versatile.py
ITEM/demos\RegexLexer.py
ITEM/demos\HideLines.py
ITEM/aaa\bbb\test.py
ITEM/Überraschung\ÜberÄÖß.py
TOOLBAR/DownloadGists.py/D:\Images\Icons\MyIconSet\Download_16x16.bmp
TOOLBAR/UploadGists.py/icons\Upload_16x16.bmp
TOOLBAR/debugger\my_debugger.py/
SETTING/ADDEXTRALINETOOUTPUT/1
SETTING/COLORIZEOUTPUT/1234567
SETTING/OPENCONSOLEONERROR/1
SETTING/PREFERINSTALLEDPYTHON/0
SETTING/STARTUP/ATSTARTUP
```
So menu item and toolbar item scripts are relative to userScriptsDir but toolbar icon path needs
to be treaten different as it might be that the image is somewhere else. So logic for icon path would be,
for saving config, if icon path **does** start with userScriptsDir then **it will be shorten** otherwise full icon path will be saved and for reading config if icon path is an existing file **no** userScriptsDir **will be added** in front of the path otherwise it will.

Something i forgot?
