### ISSUE TITLE
Can I make a panel by py script ?

### ISSUE THREAD

**Issue by balanx** [bruderstein/PythonScript#160]
I want to make a plugin, which needs a panel to show something.
It's kind of like 'function list'.

May someone give some example codes ?
Thanks

**Comment by sasumner** [comment]
This Community thread may help you:
https://community.notepad-plus-plus.org/topic/20118/handling-notifications-from-a-docked-scintilla-in-the-same-style-as-the-standard-npp-finder

Otherwise, please post "questions" (like yours) on the Community site.
This site here is for "issues" (problem reports of feature requests).

**Comment by chcg** [comment]
@balanx As stated above this is for issues with the pythonscript plugin. It is probably not intended to have a dependency to this plugin for a own one. See https://npp-user-manual.org/docs/plugins/#getting-started for starting points depending on the available programming languages.
