### ISSUE TITLE
DLL missing in Windows 7

### ISSUE THREAD

**Issue by bitagoras** [bruderstein/PythonScript#203]
In Windows 7 (still wide spread in 2021) Notepad++ opens with a error message saying that 
api-ms-win-core-version-l1-1-1.dll is missing when using release version v3.0.8 of PythonScript. Previous version v3.0.7-alpha is working normally in Windows 7.

**Comment by Speravir** [comment]
>  release version v3.0.8 of PythonScript

I first wondered … but you speak about the latest _alpha_ version. Anyway:

In the [notes for v3.0.8](https://github.com/bruderstein/PythonScript/releases/tag/v3.0.8) the following is stated:
> Updates:
>    python 3.9.4
>    docu python3.8 -> python 3.9
>    installation python3.8 -> python 3.9

But python 3.9.x does not run in Windows 7! Please, developers, stay in Python 3.8.x as long Notepad++ itself runs in Windows 7.

**Comment by bitagoras** [comment]
Ok, tank you. I was not aware about the dropped compatibility of Python do Windows 7, even it's clearly stated: [https://www.python.org/downloads/release/python-390/](https://www.python.org/downloads/release/python-390/). So I close this issue.

**Comment by Speravir** [comment]
@bitagoras: Please, reopen. The developers should get a notice about this. It’s better they close the issue ticket after making a decision, whether they want to drop Windows 7 (and Vista) support or not.

**Comment by chcg** [comment]
@Speravir There is another dependency of python 3.9 which is coming from boost 1.75 ( via https://github.com/sergey-shandar/getboost/blob/master/releases/1.75.md) which is just available for python 3.9 . So it is quite unlikely that I will go back to python 3.8 for win7 legacy support. Maybe after a first functional release for python 3 it could be checked how much effort it would take to create a branch version release with python 3.8. Currently I consider it unlikely due to lake of time for maintaining that.

See https://stackoverflow.com/questions/66718131/software-based-on-python-3-9-is-not-working-on-windows-7

**Comment by Speravir** [comment]
@chcg thank you for clarification.
