### ISSUE TITLE
ColourElement routines cannot accept alpha values

### ISSUE THREAD

**Issue by vinsworldcom** [bruderstein/PythonScript#276]
According to Scintilla docs, the [`SCI_GET/SETELEMENTCOLOUR`](https://www.scintilla.org/ScintillaDoc.html#SCI_SETELEMENTCOLOUR) APIs take and return [alphaColour](https://www.scintilla.org/ScintillaDoc.html#alpha).  However, the PythonScript implementation uses COLORREF which can only handle RGB, not RGBA (A = alpha).

Actually, there are more Scintilla APIs that use this:

[SCI_SETELEMENTCOLOUR](https://www.scintilla.org/ScintillaDoc.html#SCI_SETELEMENTCOLOUR)(int element, [colouralpha](https://www.scintilla.org/ScintillaDoc.html#colouralpha) colourElement)
[SCI_GETELEMENTCOLOUR](https://www.scintilla.org/ScintillaDoc.html#SCI_GETELEMENTCOLOUR)(int element) → colouralpha

[SCI_GETELEMENTBASECOLOUR](https://www.scintilla.org/ScintillaDoc.html#SCI_GETELEMENTBASECOLOUR)(int element) → colouralpha

[SCI_SETREPRESENTATIONCOLOUR(const char *encodedCharacter, colouralpha colour)](https://www.scintilla.org/ScintillaDoc.html#SCI_SETREPRESENTATIONCOLOUR)
[SCI_GETREPRESENTATIONCOLOUR(const char *encodedCharacter) → colouralpha](https://www.scintilla.org/ScintillaDoc.html#SCI_GETREPRESENTATIONCOLOUR)

[SCI_MARKERSETFORETRANSLUCENT(int markerNumber, colouralpha fore)](https://www.scintilla.org/ScintillaDoc.html#SCI_MARKERSETFORETRANSLUCENT)
[SCI_MARKERSETBACKTRANSLUCENT(int markerNumber, colouralpha back)](https://www.scintilla.org/ScintillaDoc.html#SCI_MARKERSETBACKTRANSLUCENT)
[SCI_MARKERSETBACKSELECTEDTRANSLUCENT(int markerNumber, colouralpha back)](https://www.scintilla.org/ScintillaDoc.html#SCI_MARKERSETBACKSELECTEDTRANSLUCENT)

**Comment by chcg** [comment]
@vinsworldcom See checkin comment on:

Revision: 1e090b73d025ceae90951f34157caffdaef22295
Message:
- update to N++ interfaces for 8.4.7 with scintilla 5.3.1 and lexilla 5.2.0
- still open issue: handling of colouralpha and related calls, currently just handled like colour, so alpha info is missing

So I'm aware of the problem. I think it needs to be handled by the pythonscript https://github.com/bruderstein/PythonScript/blob/master/PythonScript/src/CreateWrapper.py otherwise the changes to https://github.com/bruderstein/PythonScript/blob/master/PythonScript/src/ScintillaWrapperGenerated.cpp are lost on next integration of Scintilla changes.

**Comment by vinsworldcom** [comment]
@chcg great feedback. Thank you. I'm still a little lost as to how python script gets put together but certainly happy with the product!

I'm using the artifact of my commit now and it's working fine as expected, but understand that with an upgrade those changes I made will get over written. I basically treat color alpha as just an integer (32 bits)

Cheers.

**Comment by chcg** [comment]
@vinsworldcom Could you please check if the change is ok for your needs.

**Comment by vinsworldcom** [comment]
@chcg seems to work fine for the use case I've been testing (`set/getElementColour()`)!

Thank you!  Shall I go ahead and close PR #277 ?
