### ISSUE TITLE
Script hangs when using notepad.runMenuCommand with non-existent menu items

### ISSUE THREAD

**Issue by Ekopalypse** [bruderstein/PythonScript#305]
Using something like

```py
notepad.runMenuCommand("abc", "def")
```
 leads to hang the current script.
 Tested with
 `Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]`
 and `Notepad++ v8.5.5   (64-bit)`

**Comment by Ekopalypse** [comment]
@chcg - may I ask what exactly, OS and VS version, you are currently using?
The reason for the question is that I have not been able to get Intellisense to work for a few VS versions.
I can build the project without any problems, but when I work in VS, every function is reported as invalid and I don't get any real errors, which makes contributing code a bit difficult for an inexperienced cpp programmer like me.

**Comment by chcg** [comment]
@Ekopalypse 
Win10 22H2
VS2022 17.7

Have you replaced 
https://github.com/bruderstein/PythonScript/blob/master/PythonScript/project/packages.config
with
https://github.com/bruderstein/PythonScript/blob/master/PythonScript/project/packages_appveyor.config

and

https://github.com/bruderstein/PythonScript/blob/master/PythonScript/project/PythonSettings.props
with
https://github.com/bruderstein/PythonScript/blob/master/PythonScript/project/PythonSettings_appveyor.props

Otherwise you need a self compiled python version like Dave did.

**Comment by Ekopalypse** [comment]
@chcg - thanks, copying the PythonSettings_appveyor.props has solved the problem. I'm still confused why this is the solution and was I able to build the DLL but the Intellisense stuff didn't work at all. I mean it reported that all the default headers like windows.h, stdarg.h .... were missing. hmmm... but, you don't look a gift horse in the mouth :-). Thanks again.
Now hopefully I can figure out why the reported problem is happening and create a fix.

**Comment by Ekopalypse** [comment]
> copying the PythonSettings_appveyor.props has solved the problem.

didn't last long ... :-(

![image](https://github.com/bruderstein/PythonScript/assets/47723516/f941e7f6-d0e2-4f82-b1cc-f75665104d46)

**Comment by chcg** [comment]
I typically don't use the solution under https://github.com/bruderstein/PythonScript/blob/master/PythonScript/project/PythonScript2010.sln, but https://github.com/bruderstein/PythonScript/blob/master/PythonScript.sln and for x64 instead of Win32. Maybe there is some relation to the usage of precompiled headers.
