### ISSUE TITLE
Possible to get same filepath in multiple tabs using notepad.saveAs()

### ISSUE THREAD

**Issue by alankilborn** [bruderstein/PythonScript#318]
Normally, Notepad++ keeps the user from having the same file(path) open in multiple tabs (except for the case of a "cloned" document).

With PythonScript, it is possible to subvert Notepad++'s protection from the situation, e.g.:

```py
for j in (1, 2, 3):
    notepad.new()
    editor.setText('one line only with no ending')
    notepad.saveAs('foo.txt')
```

Running this script will result in three tabs in Notepad++ that all refer to the same file.  This shouldn't be allowed to happen.

Notepad++ 8.6, 64-bit with PS 3.0.16.0.

**Comment by chcg** [comment]
see https://github.com/bruderstein/PythonScript/blob/50fd4982307041efa963788d6d352c398039f406/PythonScript/src/NotepadPlusWrapper.cpp#L222-L230

saveAs is just a wrapper around N++ NPPM_SAVECURRENTFILEAS provided to be used by e.g. plugins. I think if having multiple tabs referring to the same filebuffer should not be allowed that should be blocked by N++ itself. Otherwise a bookkeeping needs to be added to PS to avoid such a situation.

@alankilborn Do you have a solution for this in mind how this could be handled on PS side?

**Comment by alankilborn** [comment]
>I think if having multiple tabs referring to the same filebuffer should not be allowed that should be blocked by N++ itself

I agree (since I now know that it is just a shallow wrapper in PS).
I will create a issue against Notepad++ for this.

---

>What are the problems with the current behaviour?

If you get multiple N++ tabs referring to the same file (for this issue's situation, NOT for a usual cloned file), if you modify and save one and then switch to another, you get the "file has been modified--reload?" prompt.

**Comment by alankilborn** [comment]
>Do you have a solution for this in mind how this could be handled on PS side?

I suppose PS could look through all the tabs to see if the file is already there.
