### ISSUE TITLE
[Suggestion] Display Console on Error

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#76]
When testing a script, you want to know if there's any error and what it is.
You manually open the Console.

I think it would be very helpful if the Console should be automatically displayed on error.

Thank you.

**Comment by sasumner** [comment]
Maybe some interesting related links? :

https://notepad-plus-plus.org/community/topic/13277/pythonscript-show-console-on-error

posting by me here:
https://notepad-plus-plus.org/community/topic/14130/hide-or-toggle-find-results-panel-with-keyboard-command

**Comment by Yaron10** [comment]
@sasumner,

Thank you for the links.

So I'm not the first user addressing this issue.
I think it would be good to integrate this option in PS (with or w/o a user preference).

**Comment by Yaron10** [comment]
> and its tab activated (if not already, in a multitab situation--I have the Find-result panel and PS Console as multi-tab in a single window) when PS code writes something to the console.

Good point.
:+1:

**Comment by Yaron10** [comment]
> but could be any console write

If you mean any `console.write()` in a script, I think it should depend on a (separate) user-preference.

**Comment by sasumner** [comment]
@Yaron10 , maybe so...maybe so...  :)
As always, with software things get complicated fast...deserves some well-thought-out design!

**Comment by Yaron10** [comment]
Opening/activating the console on error can be implemented even without a user-preference IMO.
`console.write()` in a script is fundamentally different and should therefore depend on a user-preference.

**Comment by Yaron10** [comment]
Any error message not initiated directly by the user.

If implemented, flashing NPP window can be a nice addition.
And `console.writeError()` (like `console.write()`) can have another parameter `activateConsloe` defaulted to `false`.

**Comment by ClaudiaFrank** [comment]
I wasn't clear - if you start a subprocess and try to do something with it, it might return an
output like "not supported with this version". How should a program know this?
What I can think of is that PS treats all messages which are send to stderr as error messages,
but messages sent to stdout should be treated as non-error messages which would mean
if someone is redirecting stdout to stderr it would be seen as error.

**Comment by Yaron10** [comment]
I've never tried starting a sub-process nor am I fully familiar with redirecting stdout to stderr.
So I believe your suggestion is clever as always. :)

Thank you.

**Comment by sasumner** [comment]
Maybe the low-hanging fruit is best dealt with first.  Many times I run a script and something unexpected happens, and my editor tab text doesn't change as I expect, and I am left wondering...because the PS Console is not currently being shown.  When I then show the PS console I see something like this:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined
>>>

So as a first pass, I would think that anytime a "traceback" is generated, the PS console should be shown to the user if not currently visible.

I think trying to catch things like this example with this kind of feature is a bit ambitious:  `...start a 
subprocess ...it might return an output like "not supported with this version"`.
