### ISSUE TITLE
Update MENUCOMMAND list

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#91]
Quite a few commands are missing in the MENUCOMMAND class (e.g. Search -> Find Results Window).
Could you please update the list?

Thank you.

**Comment by chcg** [comment]
Means update of docu https://github.com/bruderstein/PythonScript/blob/master/docs/source/enums.rst to adapt to the current state of the N++ interface. Scintilla parts are generated and needn't be modified.

**Comment by Yaron10** [comment]
@chcg,

:+1: 
Thank you.

**Comment by ClaudiaFrank** [comment]
Will have a look - thought the enums are uptodate.
wip

**Comment by Yaron10** [comment]
@ClaudiaFrank,

:+1: 
Thank you.

**Comment by ClaudiaFrank** [comment]
From code point of view those messages are missing
IDM_DEBUGINFO
IDM_CONFUPDATERPROXY
IDM_SYSTRAYPOPUP
IDM_CMDLINEARGUMENTS
IDM_ONLINESUPPORT
nothing really useful here but of course can be included in order to have all messages available wrapped.

From documentation point of view ~110 messages are missing - needs to be updated (will do so)

But the message Yaron was pointing to is not part of those as it is not exposed via menuCmdID.h
which makes me think if there are even more menu functions which aren't in menuCmdID.h
What to do about those?

**Comment by Yaron10** [comment]
Hello Claudia,

Thank you for working on this issue. I appreciate it.

> But the message Yaron was pointing to is not part of those as it is not exposed via menuCmdID.h,
which makes me think, whether there are even more menu functions which aren't in menuCmdID.h.
What to do about those?

I assume the question was referred to @chcg.
But I just remembered I had come across that command in `menuCmdID.h`.
And indeed there it is: `#define    IDM_FOCUS_ON_FOUND_RESULTS      (IDM_SEARCH + 45)`.

**Comment by ClaudiaFrank** [comment]
thx for finding this :-)

**Comment by Yaron10** [comment]
:+1:  :)
